// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidPb.proto

package com.example.thai.bp;

public interface SortResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SortResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
