// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidPb.proto

package com.example.thai.bp;

public interface SortRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SortRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sort_val = 1;</code>
   */
  int getSortVal();
}
